2021-07-03 10:36:49.506 [error] emulator Error in process <0.8236.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.Mix.Error',message => <<"Application configuration returned from application/0 should be a keyword list">>,mix => true},[{'Elixir.Mix',raise,1,[{file,"lib/mix.ex"},{line,436}]},{'Elixir.Mix.Tasks.Compile.App',merge_project_application,2,[{file,"lib/mix/tasks/compile.app.ex"},{line,223}]},{'Elixir.Mix.Tasks.Compile.App',run,1,[{file,"lib/mix/tasks/compile.app.ex"},{line,156}]},{'Elixir.Mix.Task',run_task,3,[{file,"lib/mix/task.ex"},{line,394}]},{'Elixir.Mix.Tasks.Compile.All',run_compiler,2,[{file,"lib/mix/tasks/compile.all.ex"},{line,90}]},{'Elixir.Mix.Tasks.Compile.All',compile,4,[{file,"lib/mix/tasks/compile.all.ex"},{line,70}]},{'Elixir.Mix.Tasks.Compile.All',with_logger_app,2,[{file,"lib/mix/tasks/compile.all.ex"},{line,57}]},{'Elixir.Mix.Tasks.Compile.All',run,1,[{file,"lib/mix/tasks/compile.all.ex"},{line,35}]}]}
2021-07-03 11:31:21.223 [error] emulator Error in process <0.16062.0> with exit value:
{function_clause,[{'Elixir.ElixirLS.LanguageServer.Providers.DocumentSymbols',build_symbol_information_hierarchical,[<<"file:///home/emoura/Workspace/covid-zone/cz_user_tests/cz_user/config/config.exs">>,nil],[{file,"lib/language_server/providers/document_symbols.ex"},{line,285}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1411}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1411}]},{'Elixir.ElixirLS.LanguageServer.Providers.DocumentSymbols',symbols,3,[{file,"lib/language_server/providers/document_symbols.ex"},{line,28}]},{'Elixir.ElixirLS.LanguageServer.Server','-handle_request_async/2-fun-0-',3,[{file,"lib/language_server/server.ex"},{line,770}]}]}
2021-07-03 11:31:35.176 [error] emulator Error in process <0.16068.0> with exit value:
{function_clause,[{'Elixir.ElixirLS.LanguageServer.Providers.DocumentSymbols',build_symbol_information_hierarchical,[<<"file:///home/emoura/Workspace/covid-zone/cz_user_tests/cz_user/config/config.exs">>,nil],[{file,"lib/language_server/providers/document_symbols.ex"},{line,285}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1411}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1411}]},{'Elixir.ElixirLS.LanguageServer.Providers.DocumentSymbols',symbols,3,[{file,"lib/language_server/providers/document_symbols.ex"},{line,28}]},{'Elixir.ElixirLS.LanguageServer.Server','-handle_request_async/2-fun-0-',3,[{file,"lib/language_server/server.ex"},{line,770}]}]}
2021-07-03 11:31:59.713 [error] emulator Error in process <0.16076.0> with exit value:
{function_clause,[{'Elixir.ElixirLS.LanguageServer.Providers.DocumentSymbols',build_symbol_information_hierarchical,[<<"file:///home/emoura/Workspace/covid-zone/cz_user_tests/cz_user/config/config.exs">>,nil],[{file,"lib/language_server/providers/document_symbols.ex"},{line,285}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1411}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1411}]},{'Elixir.ElixirLS.LanguageServer.Providers.DocumentSymbols',symbols,3,[{file,"lib/language_server/providers/document_symbols.ex"},{line,28}]},{'Elixir.ElixirLS.LanguageServer.Server','-handle_request_async/2-fun-0-',3,[{file,"lib/language_server/server.ex"},{line,770}]}]}
2021-07-03 11:32:00.948 [error] emulator Error in process <0.16080.0> with exit value:
{function_clause,[{'Elixir.ElixirLS.LanguageServer.Providers.DocumentSymbols',build_symbol_information_hierarchical,[<<"file:///home/emoura/Workspace/covid-zone/cz_user_tests/cz_user/config/config.exs">>,nil],[{file,"lib/language_server/providers/document_symbols.ex"},{line,285}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1411}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1411}]},{'Elixir.ElixirLS.LanguageServer.Providers.DocumentSymbols',symbols,3,[{file,"lib/language_server/providers/document_symbols.ex"},{line,28}]},{'Elixir.ElixirLS.LanguageServer.Server','-handle_request_async/2-fun-0-',3,[{file,"lib/language_server/server.ex"},{line,770}]}]}
2021-07-03 11:32:05.236 [error] emulator Error in process <0.16090.0> with exit value:
{function_clause,[{'Elixir.ElixirLS.LanguageServer.Providers.DocumentSymbols',build_symbol_information_hierarchical,[<<"file:///home/emoura/Workspace/covid-zone/cz_user_tests/cz_user/config/config.exs">>,nil],[{file,"lib/language_server/providers/document_symbols.ex"},{line,285}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1411}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1411}]},{'Elixir.ElixirLS.LanguageServer.Providers.DocumentSymbols',symbols,3,[{file,"lib/language_server/providers/document_symbols.ex"},{line,28}]},{'Elixir.ElixirLS.LanguageServer.Server','-handle_request_async/2-fun-0-',3,[{file,"lib/language_server/server.ex"},{line,770}]}]}
2021-07-03 11:32:06.299 [error] emulator Error in process <0.16094.0> with exit value:
{function_clause,[{'Elixir.ElixirLS.LanguageServer.Providers.DocumentSymbols',build_symbol_information_hierarchical,[<<"file:///home/emoura/Workspace/covid-zone/cz_user_tests/cz_user/config/config.exs">>,nil],[{file,"lib/language_server/providers/document_symbols.ex"},{line,285}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1411}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1411}]},{'Elixir.ElixirLS.LanguageServer.Providers.DocumentSymbols',symbols,3,[{file,"lib/language_server/providers/document_symbols.ex"},{line,28}]},{'Elixir.ElixirLS.LanguageServer.Server','-handle_request_async/2-fun-0-',3,[{file,"lib/language_server/server.ex"},{line,770}]}]}
2021-07-03 11:32:07.487 [error] emulator Error in process <0.16099.0> with exit value:
{function_clause,[{'Elixir.ElixirLS.LanguageServer.Providers.DocumentSymbols',build_symbol_information_hierarchical,[<<"file:///home/emoura/Workspace/covid-zone/cz_user_tests/cz_user/config/config.exs">>,nil],[{file,"lib/language_server/providers/document_symbols.ex"},{line,285}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1411}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1411}]},{'Elixir.ElixirLS.LanguageServer.Providers.DocumentSymbols',symbols,3,[{file,"lib/language_server/providers/document_symbols.ex"},{line,28}]},{'Elixir.ElixirLS.LanguageServer.Server','-handle_request_async/2-fun-0-',3,[{file,"lib/language_server/server.ex"},{line,770}]}]}
2021-07-03 11:32:27.368 [error] emulator Error in process <0.16121.0> with exit value:
{function_clause,[{'Elixir.Config',config,[cz_user,'Elixir.CzUser.Repo'],[{file,"lib/config.ex"},{line,119}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,680}]},{elixir,recur_eval,3,[{file,"src/elixir.erl"},{line,280}]},{elixir,eval_forms,3,[{file,"src/elixir.erl"},{line,265}]},{'Elixir.Code',eval_string_with_error_handling,3,[{file,"lib/code.ex"},{line,341}]},{'Elixir.Config','__eval__!',3,[{file,"lib/config.ex"},{line,255}]},{'Elixir.Mix.Tasks.Loadconfig',load_compile,1,[{file,"lib/mix/tasks/loadconfig.ex"},{line,49}]},{'Elixir.Mix.Task',run_task,3,[{file,"lib/mix/task.ex"},{line,394}]}]}
2021-07-03 11:37:15.090 [error] emulator Error in process <0.16829.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.SyntaxError',column => 2,description => <<"syntax error before: migration_foreign_key">>,file => <<"/home/emoura/Workspace/covid-zone/cz_user_tests/cz_user/config/config.exs">>,line => 15},[{'Elixir.Code',eval_string_with_error_handling,3,[{file,"lib/code.ex"},{line,340}]},{'Elixir.Config','__eval__!',3,[{file,"lib/config.ex"},{line,255}]},{'Elixir.Mix.Tasks.Loadconfig',load_compile,1,[{file,"lib/mix/tasks/loadconfig.ex"},{line,49}]},{'Elixir.Mix.Task',run_task,3,[{file,"lib/mix/task.ex"},{line,394}]},{'Elixir.ElixirLS.LanguageServer.Build',reload_project,0,[{file,"lib/language_server/build.ex"},{line,157}]},{'Elixir.ElixirLS.LanguageServer.Build','-build/3-fun-0-',3,[{file,"lib/language_server/build.ex"},{line,16}]},{timer,tc,1,[{file,"timer.erl"},{line,166}]}]}
2021-07-06 11:45:32.081 [error] <0.540.0> gen_server <0.540.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,5},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420
2021-07-06 11:45:32.081 [error] <0.543.0> gen_server <0.543.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,8},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420
2021-07-06 11:45:32.081 [error] <0.545.0> gen_server <0.545.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,10},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420
2021-07-06 11:45:32.082 [error] <0.536.0> gen_server <0.536.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420
2021-07-06 11:45:32.082 [error] <0.541.0> gen_server <0.541.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,6},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420
2021-07-06 11:45:32.083 [error] <0.538.0> gen_server <0.538.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,3},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420
2021-07-06 11:45:32.083 [error] <0.537.0> gen_server <0.537.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,2},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420
2021-07-06 11:45:32.084 [error] <0.539.0> gen_server <0.539.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,4},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420
2021-07-06 11:45:32.084 [error] <0.537.0> CRASH REPORT Process <0.537.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,2},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in 'Elixir.Connection':enter_stop/5 line 686
2021-07-06 11:45:32.085 [error] <0.540.0> CRASH REPORT Process <0.540.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,5},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in 'Elixir.Connection':enter_stop/5 line 686
2021-07-06 11:45:32.085 [error] <0.535.0> Supervisor {<0.535.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.534.0>,2} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,2},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{...},...], <0.534.0>, #Ref<0.531938973.2697592833.240953>) at <0.537.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,2},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in context child_terminated
2021-07-06 11:45:32.086 [error] <0.536.0> CRASH REPORT Process <0.536.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in 'Elixir.Connection':enter_stop/5 line 686
2021-07-06 11:45:32.086 [error] <0.544.0> gen_server <0.544.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,9},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420
2021-07-06 11:45:32.086 [error] <0.542.0> gen_server <0.542.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,7},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420
2021-07-06 11:45:32.087 [error] <0.565.0> gen_server <0.565.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,2},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420
2021-07-06 11:45:32.087 [error] <0.539.0> CRASH REPORT Process <0.539.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,4},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in 'Elixir.Connection':enter_stop/5 line 686
2021-07-06 11:45:32.088 [error] <0.535.0> Supervisor {<0.535.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.534.0>,5} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,5},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{...},...], <0.534.0>, #Ref<0.531938973.2697592833.240953>) at <0.540.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,5},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in context child_terminated
2021-07-06 11:45:32.088 [error] <0.538.0> CRASH REPORT Process <0.538.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,3},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in 'Elixir.Connection':enter_stop/5 line 686
2021-07-06 11:45:32.088 [error] <0.542.0> CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,7},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in 'Elixir.Connection':enter_stop/5 line 686
2021-07-06 11:45:32.088 [error] <0.565.0> CRASH REPORT Process <0.565.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,2},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in 'Elixir.Connection':enter_stop/5 line 686
2021-07-06 11:45:32.089 [error] <0.544.0> CRASH REPORT Process <0.544.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,9},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in 'Elixir.Connection':enter_stop/5 line 686
2021-07-06 11:45:32.089 [error] <0.541.0> CRASH REPORT Process <0.541.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,6},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in 'Elixir.Connection':enter_stop/5 line 686
2021-07-06 11:45:32.089 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,8},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in 'Elixir.Connection':enter_stop/5 line 686
2021-07-06 11:45:32.090 [error] <0.535.0> Supervisor {<0.535.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.534.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{...},...], <0.534.0>, #Ref<0.531938973.2697592833.240953>) at <0.536.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in context child_terminated
2021-07-06 11:45:32.091 [error] <0.545.0> CRASH REPORT Process <0.545.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,10},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in 'Elixir.Connection':enter_stop/5 line 686
2021-07-06 11:45:32.091 [error] <0.566.0> gen_server <0.566.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,5},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420
2021-07-06 11:45:32.092 [error] <0.535.0> Supervisor {<0.535.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.534.0>,4} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,4},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{...},...], <0.534.0>, #Ref<0.531938973.2697592833.240953>) at <0.539.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,4},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in context child_terminated
2021-07-06 11:45:32.092 [error] <0.535.0> Supervisor {<0.535.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.534.0>,4} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,4},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{...},...], <0.534.0>, #Ref<0.531938973.2697592833.240953>) at <0.539.0> exit with reason reached_max_restart_intensity in context shutdown
2021-07-06 11:45:32.093 [error] <0.535.0> Supervisor {<0.535.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.534.0>,10} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,10},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},...], <0.534.0>, #Ref<0.531938973.2697592833.240953>) at <0.545.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,10},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in context shutdown_error
2021-07-06 11:45:32.093 [error] <0.535.0> Supervisor {<0.535.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.534.0>,9} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,9},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{...},...], <0.534.0>, #Ref<0.531938973.2697592833.240953>) at <0.544.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,9},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in context shutdown_error
2021-07-06 11:45:32.094 [error] <0.535.0> Supervisor {<0.535.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.534.0>,8} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,8},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{...},...], <0.534.0>, #Ref<0.531938973.2697592833.240953>) at <0.543.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,8},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in context shutdown_error
2021-07-06 11:45:32.094 [error] <0.535.0> Supervisor {<0.535.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.534.0>,7} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,7},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{...},...], <0.534.0>, #Ref<0.531938973.2697592833.240953>) at <0.542.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,7},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in context shutdown_error
2021-07-06 11:45:32.095 [error] <0.535.0> Supervisor {<0.535.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.534.0>,6} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,6},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{...},...], <0.534.0>, #Ref<0.531938973.2697592833.240953>) at <0.541.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,6},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in context shutdown_error
2021-07-06 11:45:32.096 [error] <0.535.0> Supervisor {<0.535.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.534.0>,3} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,3},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{...},...], <0.534.0>, #Ref<0.531938973.2697592833.240953>) at <0.538.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,3},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in context shutdown_error
2021-07-06 11:45:32.096 [error] <0.535.0> Supervisor {<0.535.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.534.0>,2} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,2},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{...},...], <0.534.0>, #Ref<0.531938973.2697592833.240953>) at <0.565.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,2},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in context shutdown_error
2021-07-06 11:45:32.096 [error] <0.533.0> Supervisor 'Elixir.CzUser.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.CzUser.Repo', 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.531938973.2697592833.240952>,opts => [{timeout,15000},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.534.0> exit with reason killed in context child_terminated
2021-07-06 11:45:32.096 [error] <0.533.0> Supervisor 'Elixir.CzUser.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.CzUser.Repo', 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.531938973.2697592833.240952>,opts => [{timeout,15000},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.534.0> exit with reason reached_max_restart_intensity in context shutdown
2021-07-06 11:45:32.096 [error] <0.532.0> Supervisor 'Elixir.CzUser.Supervisor' had child 'Elixir.CzUser.Repo' started with 'Elixir.CzUser.Repo':start_link([]) at <0.533.0> exit with reason shutdown in context child_terminated
2021-07-06 11:45:32.097 [error] <0.571.0> gen_server <0.571.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420
2021-07-06 11:45:32.097 [error] <0.571.0> CRASH REPORT Process <0.571.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in 'Elixir.Connection':enter_stop/5 line 686
2021-07-06 11:45:32.097 [error] <0.572.0> gen_server <0.572.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,2},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420
2021-07-06 11:45:32.097 [error] <0.572.0> CRASH REPORT Process <0.572.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,2},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in 'Elixir.Connection':enter_stop/5 line 686
2021-07-06 11:45:32.097 [error] <0.574.0> gen_server <0.574.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,4},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420
2021-07-06 11:45:32.098 [error] <0.573.0> gen_server <0.573.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,3},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420
2021-07-06 11:45:32.098 [error] <0.573.0> CRASH REPORT Process <0.573.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,3},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in 'Elixir.Connection':enter_stop/5 line 686
2021-07-06 11:45:32.098 [error] <0.574.0> CRASH REPORT Process <0.574.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,4},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in 'Elixir.Connection':enter_stop/5 line 686
2021-07-06 11:45:32.098 [error] <0.575.0> gen_server <0.575.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,5},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420
2021-07-06 11:45:32.098 [error] <0.575.0> CRASH REPORT Process <0.575.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,5},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420 in 'Elixir.Connection':enter_stop/5 line 686
2021-07-06 11:45:32.099 [error] <0.576.0> gen_server <0.576.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,message => nil,term => [{pool_index,6},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.CzUser.Repo'},{telemetry_prefix,[cz_user,repo]},{otp_app,cz_user},{timeout,15000},{username,<<"postgres">>},{password,<<"postgres">>},{hostname,<<"localhost">>},{show_sensitive_data_on_connection_error,true},{pool_size,10},{pool,'Elixir.DBConnection.ConnectionPool'}]} in 'Elixir.Keyword':'fetch!'/2 line 420
2021-07-07 10:55:28.068 [error] <0.442.0> Supervisor {<0.442.0>,amqp_channel_sup_sup} had child channel_sup started with amqp_channel_sup:start_link(network, <0.441.0>, <<"client 127.0.0.1:59829 -> 127.0.0.1:5672">>) at undefined exit with reason shutdown in context shutdown_error
